language: node_js

stages:
  - prepare cache
  - lint
  - build
  - test

cache:
  directories:
  - node_modules # NPM packages

jobs:
  include:
    - stage: prepare cache
      node_js: node
      script: true

    - stage: lint
      node_js: node
      script: npm run lint-tsc

    - stage: build
      node_js: node
      script: npm run build-tsc

    - &test
      stage: test
      node_js: 8
      before_script:
        ## Spin up container
        - cd test/docker/
        - docker-compose -f docker-compose.test.yml up -d

        ## Sleep before performing commands on container
        - sleep 240

        - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"')
        - export GITLAB_URL=$(docker exec -it gitlab bash -lc 'printf "%q" "${GITLAB_URL}"')
      script: npm run test

    - <<: *test
      node_js: lts/*

    - <<: *test
      node_js: 9

    - <<: *test
      node_js: node